### ISSUE TITLE
Veröffentlichungsdatum 

### ISSUE THREAD

**Issue by mrchristian** [TIBHannover/co-site-glossar#6]
Please add a time stamp when publishing.

17. Dezember 2024

This will help contributors know if we have updated the doc

We should use CET and have HH:mm:ss

https://github.com/TIBHannover/co-site-glossar/blob/main/_quarto.yml

**Comment by calnfynn** [comment]
done

**Comment by mrchristian** [comment]
I saw that for https://github.com/TIBHannover/co-site-glossar/blob/main/_quarto.yml

We can add 

date: last-modified

and format as we like also

https://quarto.org/docs/reference/dates.html

**Comment by mrchristian** [comment]
Which file did you edit to add time to date? I thought it came from the .yml file?

**Comment by calnfynn** [comment]
in _quarto.yml
```
book:
  date: now
  date-format: DD. MMMM YYYY, HH:mm:ss
```
